version: '3'
services:
  app:
    build: .
    container_name: personalteacher-app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/psback
      - JWT_SECRET=your_jwt_secret_here
      - NODE_ENV=development
      - PORT=3333
    ports:
      - "3333:3333"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:13-alpine
    container_name: postgres-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: psback
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: